# Welcome to Jekyll!

# Website settings
title: "Javier Martín Alonso"
description: "Blog de Javier Martín Alonso,usando Jekyll y github pages."
keywords: "Javier,Javier Martín,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "https://javiermartinalonso.github.io"
name: javiermartinalonso
img_logo_path: 'static/img/favicon.ico'

# author
author:
  name: 'Javier'
  first_name: 'Martín'
  last_name: 'Alonso'
  email: 'javimartinalonso@gmail.com'
  linkldn: 'https://www.linkedin.com/in/javimartinalonso'
  facebook_username: 'javier.martinalonso.73'
  youtube_canal_name: 'https://www.youtube.com/user/jmartal'
  github_username: 'javiermartinalonso'
  head_img: 'static/img/blog/javi.jpg'
  desc: 'Soy ingeniero informático y me gano la vida desarrollando aplicaciones java empresariales. La vida es un proceso de aprendizaje continuo, por lo que desarrollar este blog me hace el trabajo más riguroso.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'
    
  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'es'
    flag: 'static/img/flags/Spain.png'
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'https://javiermartinalonso.github.io/static/img/blog'

# Comento la seccion de donate no la necesito por ahora
# donate
#donate:
#  wechat: 'static/img/pay/wechat.png'
#  alipay: 'static/img/pay/alipay.png'

# comment
#changyan:
#  appid: cysfY7ULn
#  conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: javiermartinalonso
#   public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

#feed
feedburner:
  uri: javiermartinalonso

# counter
counter:
  name: javiermartinalonso
#   public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
#   uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
#   uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
#   id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
