-- Ejemplo de creacion de schema en Oracle



CREATE TABLESPACE NOTIFICATION_DES DATAFILE 
  '+DATA' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE USER NOTIFICATION_DES
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE NOTIFICATION_DES
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for NOTIFICATION_DES 
  GRANT CONNECT TO NOTIFICATION_DES;
  GRANT RESOURCE TO NOTIFICATION_DES;
  ALTER USER NOTIFICATION_DES DEFAULT ROLE ALL;
  -- 1 Tablespace Quota for NOTIFICATION_DES 
  ALTER USER NOTIFICATION_DES QUOTA UNLIMITED ON NOTIFICATION_DES;